#!/usr/bin/env bash

#
# This will initialize an Arch Linux system with all the essentials.
# The script should be run during the chroot step of the installation.
#

(($(id -u) > 0)) && echo "Must be root" && exit 1

ping -c 2 8.8.8.8 &> /dev/null || {
  echo "Network connection is required to continue"
  exit 1
}

# Copy contents of root folder to /
cp -rf ./__root/* /

# Make sudoers files world unreadable
chmod o-rwx /etc/sudoers.d/*

# Filesystem optimizations (for SSDs)
sed -i "s/relatime/noatime/g" /etc/fstab
systemctl enable fstrim.timer

# Prevent system OOM
systemctl enable systemd-oomd.service

# Generate locales
locale-gen

# Configure the network
systemctl enable systemd-networkd.service
systemctl enable systemd-resolved.service

read -r -p "Will you be using Wi-Fi? (y/N) " wifi
[[ "${wifi,,}" == "y" ]] && {
  pacman -S --noconfirm --needed iwd
  systemctl enable iwd.service
}

read -r -p "Will you be using WireGuard? (y/N) " wg
[[ "${wg,,}" == "y" ]] && pacman -S --noconfirm --needed wireguard-tools systemd-resolvconf

read -r -p "Will you be using Bluetooth? (y/N) " bluetooth
[[ "${bluetooth,,}" == "y" ]] && {
  pacman -S --noconfirm --needed bluez bluez-utils
  systemctl enable bluetooth.service
}

# Set the hostname
read -r -p "Set hostname: " hostname
echo "${hostname,,}" > /etc/hostname
printf "Hostname set to %s." "${hostname,,}"

# Enable CPU frequency scaling
pacman -S --noconfirm --needed power-profiles-daemon
systemctl enable power-profiles-daemon.service

# Create the default user 1000 if he doesn't exist
getent passwd 1000 &> /dev/null || {
  read -r -p "Create the default user with sudo access. Username: " username
  useradd -m -G wheel -s /usr/bin/bash "${username,,}"
  passwd "${username,,}"
  printf "Created user %s." "${username,,}"
}

# Use realtime privileges for user 1000 (pro audio)
pacman -S --noconfirm --needed realtime-privileges
gpasswd -a "$(getent passwd 1000 | cut -d ":" -f 1)" realtime

# Configure the time
read -r -p "Configure timezone (default: UTC) " timezone
tz_file="/usr/share/zoneinfo/${timezone:-UTC}"
if [ -f "${tz_file}" ]; then
  ln -sf "${tz_file}" /etc/localtime
else
  printf "Timezone %s not found. Setting /etc/localtime to UTC instead.\n" "${timezone}"
  ln -sf /usr/share/zoneinfo/UTC /etc/localtime
fi

systemctl enable systemd-timesyncd.service

hwclock --systohc

# Regenerate initramfs image because of the added custom config
mkinitcpio -P

# Bootloader
read -r -p "Set up bootloader? Only run this if you have ESP mounted to /boot (y/N) " bootloader
if [[ "${bootloader,,}" == "y" ]]; then 
  mkdir -p /boot/loader/entries
  bootctl install
  systemctl enable systemd-boot-update.service
  cat << EOF > /boot/loader/loader.conf
default arch
timeout 3
editor no
console-mode max
EOF

  printf "\nPartition UUIDs:\n"

  uuids=()
  i=0
  for disk in /dev/disk/by-uuid/*; do
    link=$(readlink -f "$disk")
    uuid=${disk##*/}
    printf "  %d) %s -> %s\n" $i "$link" "$uuid"
    uuids+=(uuid)
    ((i++))
  done

  printf "\nFound %d devices.\n" $i

  ((i--))

  while true; do
    read -r -p "Select your root partition: (0-${i}) " selected
    if [[ ! $selected =~ ^[0-9]+$ ]]; then continue; fi
    if ! ((selected >= 0 && selected <= i)); then continue; fi
    read -r -p "Use ${uuids[$selected]}? (y/N) " ok
    if [[ "${ok,,}" == "y" ]]; then break; fi
  done

  cat << EOF > /boot/loader/entries/arch.conf
title Arch Linux
linux /vmlinuz-linux
initrd /initramfs-linux.img
options root=UUID=${uuids[$selected]} rw mitigations=off
EOF
fi # /bootloader

echo "Set the root password"
passwd

echo "Done. You should reboot now."
