#!/usr/bin/env fish

# Pre-create dirs so Stow doesn't put symlink too far up
mkdir -p $HOME/.config/fcitx5/conf
mkdir -p $HOME/.config/fish/functions
mkdir -p $HOME/.config/yazi
mkdir -p $HOME/.gnupg
mkdir -p $HOME/.local/share
mkdir -p $HOME/.ssh

set -Ux FZF_DEFAULT_OPTS "\
  --highlight-line \
  --info=inline-right \
  --ansi \
  --color=bg+:#2d3f76 \
  --color=bg:#1e2030 \
  --color=border:#589ed7 \
  --color=fg:#c8d3f5 \
  --color=gutter:#1e2030 \
  --color=header:#ff966c \
  --color=hl+:#65bcff \
  --color=hl:#65bcff \
  --color=info:#545c7e \
  --color=marker:#ff007c \
  --color=pointer:#ff007c \
  --color=prompt:#65bcff \
  --color=query:#c8d3f5:regular \
  --color=scrollbar:#589ed7 \
  --color=separator:#ff966c \
  --color=spinner:#ff007c"

set -Ux RIPGREP_CONFIG_PATH $HOME/.ripgreprc

fisher update

fish_update_completions

tldr --update

bat cache --build

if test -d $HOME/.config/yazi/flavors/catppuccin-mocha.yazi
  ya pkg upgrade
else
  ya pkg add yazi-rs/flavors:catppuccin-mocha
end
