#!/usr/bin/env bash

#
# This will install packages from lists in `__packages` dir
#

(($(id -u) > 0)) && echo "Must be root" && exit 1

lists=()

for list in "${PWD}"/__packages/*; do
  lists+=("${list##*/}")
done

while true; do
  i=0

  printf "\nAvailable package lists:\n"

  for list in "${lists[@]}"; do
    printf "  %d) %s\n" $((i+1)) "$list"
    ((i++))
  done

  read -r -p "Select (1-${i}): " selected

  if [[ ! $selected =~ ^[1-9]+$ ]]; then continue; fi
  ((selected--))
  if ((selected >= i)); then continue; fi

  pacman -S --needed --noconfirm - < "${PWD}/__packages/${lists[$selected]}"

  printf "Done installing packages from %s\n" "${lists[$selected]}"
done
